# Generated by Django 6.0.4 on 2026-04-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicationmodel',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
